#include "YouKnow106Chorus.h"

#include <algorithm>
#include <cmath>

namespace youknow106
{
namespace
{
// Aggregate charge-transfer inefficiency of the whole line, condensed to one
// pole advanced at the BBD clock rate. The MN3009's -3 dB at 12 kHz with a
// 40 kHz clock is the response of the complete part, including the rectangular
// sample-and-hold pulse at its output. That pulse already contributes
// sinc(12/40) = -1.326 dB in this model. The residual pole must therefore
// contribute -1.674 dB, not another -3 dB. Solving the discrete one-pole at
// 0.3 cycles/sample gives this update coefficient.
constexpr float transferSmear = 0.8654743f;

// Static transfer of the delay line, referred to the model's signal scale
// (1.0 = 2.6 V at the node). A plain tanh with a 2.9 V asymptote already bends
// too far below the rails: it gives about 1.2% THD at the part's 0.78 Vrms
// test point instead of the specified typical 0.3%. This generalized algebraic
// soft clip has the same approximately 2.9 V asymptote, while its exponent is
// fitted jointly to 0.3% at 0.78 Vrms and 2.5% at the 1.5 Vrms input-swing
// point. It stays linear through ordinary wet levels and bends rapidly near
// the measured window rather than colouring every signal like a tanh.
constexpr float bbdSaturationLevel = 1.1246614f; // 2.924 V at the node
constexpr float bbdSaturationExponent = 3.4541951f;

// There is no divider ahead of the line. A previous revision put one here --
// 33 kOhm against 12 kOhm -- on a reading of the schematic that the schematic
// does not support: the 100 kOhm at each line's input injects adjustable DC
// bias from VR1/VR2 and is not the lower leg of anything, and the 10 kOhm
// against 2.2 nF beside it is a low-pass pole, not an attenuator. VR1/VR2 trim
// each line's DC bias so the positive and negative clipping points are
// symmetrical during the service procedure's 10 Vpp, 1 kHz TP2 test; they do
// not set a signal gain.
//
// The voice summer ahead of the whole effect does attenuate, but it attenuates
// dry and wet alike, so it is not a chorus divider either and cannot change the
// balance the summing resistors set.

// Voiced noise floor of one line, referred to its own input. The closest
// located capture gives noise level alone, with no reference tone, calibrated
// level, weighting or stated bandwidth, so it cannot establish an SNR or an
// exact amplitude here. Modelling some floor still matters because this chorus
// has no compander; the value below remains provisional pending a calibrated
// capture.
// Independent random noise generated by each wet line at its own clock edges.
// This is the pre-OQ-03 compatibility level, preserved bit for bit.  It is a
// voiced/unknown value, not a calibrated hardware measurement.
constexpr float independentLineRandomAmplitude = 1.0e-3f;

// Support filters, from the schematic rather than from an estimate of it. Each
// side of the line carries two emitter-follower Sallen-Key sections built on
// equal 22 kOhm pairs, so each section's corner comes from its capacitors and
// its Q from their ratio alone:
//
//   Tr13 / Tr15   820 pF feedback, 680 pF shunt  ->  9.69 kHz, Q 0.549
//   Tr14 / Tr16   1.8 nF feedback, 270 pF shunt  -> 10.38 kHz, Q 1.291
//
// and the input adds one passive pole, R122 10 kOhm against C52 2.2 nF, at
// 7.23 kHz. The coupling capacitor C44/C47 adds a wet-only high-pass against
// R120/R114 100 kOhm at 15.9 Hz.
//
// This replaces a single pole at 9.9 kHz in and 9.5 kHz out, which was a guess
// at a fifth-order response rather than the response itself, and was therefore
// far too bright: four poles near 10 kHz reach -12 dB at 15 kHz where one
// reaches -4. It also settles the standing disagreement in the right
// direction. A sibling's wet path had been fitted with a *single* pole at
// 14 kHz, which cannot describe this circuit; the schematic shows why a
// single-pole fit was never going to.
constexpr float antiAliasFirstHz = 9688.0f;
constexpr float antiAliasFirstFeedbackF = 820.0e-12f;
constexpr float antiAliasFirstShuntF = 680.0e-12f;
constexpr float antiAliasSecondHz = 10377.0f;
constexpr float antiAliasSecondFeedbackF = 1.8e-9f;
constexpr float antiAliasSecondShuntF = 270.0e-12f;
constexpr float antiAliasPassiveHz = 7234.0f;   // R122 10 kOhm x C52 2.2 nF
constexpr float inputCouplingHz = 15.9155f;     // C44 0.1 uF x R120 100 kOhm
constexpr float wetOutputCouplingCapacitanceF = 1.0e-6f; // C28 / C25
constexpr float wetOutputBleedOhms = 22000.0f;
constexpr float wetMixerInputOhms = 47000.0f;

// The output's fifth pole is the BBD tap-summing node: either active output
// reaches C45/C48 2.2 nF through 3.3 kOhm, and R117/R110 47 kOhm returns the
// node to ground. Treating the active BBD output as an ideal source gives
// (3.3 kOhm || 47 kOhm) against 2.2 nF, or 23.46138 kHz. The MN3009 datasheet does
// not specify output impedance, so this is deliberately a first-order nominal
// model, not a claim that a real unit's pole lands to the hertz. A full MNA or
// wet-only sweep should replace it when one is available.
constexpr float idealSourceTapPoleHz = 23461.38f;
constexpr float reconstructionFirstHz = 9688.0f;
constexpr float reconstructionSecondHz = 10377.0f;

// The wet-mute glide is expressed relative to dry. The final IC6 summer's
// absolute 100/39 dry gain is applied after the BBDs in process(); putting it
// before them would drive their fitted nonlinearity 8.18 dB too hard.
constexpr float lineGain = Chorus::wetToDryGain;   // 39/47, -1.62 dB

std::uint32_t nextNoiseState(std::uint32_t state) noexcept
{
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return state;
}

float noiseFromState(std::uint32_t state) noexcept
{
    return static_cast<float>(state & 0xffffffu) * (2.0f / 16777215.0f) - 1.0f;
}

// Symmetric triangle over a 0..1 phase, in -1..+1.
//
// This is the shape the circuit makes, not a convenient stand-in for it. IC1b
// integrates a constant current for the whole of each half cycle -- see the
// derivation on Chorus::lfoTimingOhms -- so both flanks are straight. An RC
// relaxation oscillator would bend them, and this one is not that.
float triangle(double phase) noexcept
{
    const double folded = phase < 0.5 ? phase : 1.0 - phase;
    return static_cast<float>(folded * 4.0 - 1.0);
}

// std::sqrt is not constexpr before C++26, and settingsFor() runs once per
// sample, so the mode rates have to be folded at compile time some other way.
// Newton on x^2 = value, from a crude seed; the inputs here are all near unity
// so a fixed iteration count converges to the last bit.
constexpr double constexprSqrt(double value) noexcept
{
    if (!(value > 0.0))
        return 0.0;

    double guess = value > 1.0 ? value : 1.0;
    for (int iteration = 0; iteration < 32; ++iteration)
        guess = 0.5 * (guess + value / guess);
    return guess;
}
} // namespace

Chorus::StereoNoiseSample Chorus::correlatedRandomStep(
    std::uint32_t& commonState, std::uint32_t& orthogonalState,
    float correlation) noexcept
{
    commonState = nextNoiseState(commonState);
    orthogonalState = nextNoiseState(orthogonalState);

    const float common = noiseFromState(commonState);
    const float orthogonal = noiseFromState(orthogonalState);
    const float rho = std::isfinite(correlation)
        ? std::clamp(correlation, -1.0f, 1.0f) : 0.0f;
    const float orthogonalGain = std::sqrt(std::max(0.0f, 1.0f - rho * rho));
    return { common, rho * common + orthogonalGain * orthogonal };
}

float Chorus::deterministicToneStep(double& phase, float frequencyHz,
                                    float sampleRate) noexcept
{
    if (!std::isfinite(frequencyHz) || !std::isfinite(sampleRate)
        || sampleRate <= 0.0f)
        return 0.0f;

    phase += static_cast<double>(std::max(frequencyHz, 0.0f))
           / static_cast<double>(sampleRate);
    phase -= std::floor(phase);
    return static_cast<float>(std::sin(2.0 * 3.14159265358979323846 * phase));
}

Chorus::ModeSettings Chorus::settingsFor(ChorusMode mode) noexcept
{
    // The sweep endpoints are a *Juno-60's* measured figures, and they are
    // labelled as such deliberately: delay 1.66 ms to 5.35 ms, read from a
    // calibrated capture of that instrument. No qualifying capture of a
    // Juno-106's own chorus has been located -- a revision briefly adopted
    // 1.54-5.15 ms as one, which turned out not to exist -- and the figures
    // published for this instrument are only "about 0.5 Hz" and "about 0.8 Hz".
    //
    // The rates are split between those two facts. This instrument's own
    // schematic fixes their *ratio* exactly: Chorus::lfoTimingOhms derives
    // 6.4352941 MOhm for mode I and 3.9638889 MOhm for mode II from the mode
    // switch's T-network, so mode II runs 1.6234799 times faster. What the
    // schematic cannot give is the *scale*, because it does not print the
    // integrator capacitor. So the sibling's pair supplies the scale and only
    // the scale: its geometric mean is preserved exactly, and this instrument's
    // own ratio re-splits it. Both results still round to the published
    // about-0.5 and about-0.8. The sibling's own 1.682 ratio is superseded and
    // must not be reintroduced.
    //
    // Modes I and II differ in speed alone, not in depth: the mode line changes
    // a timing resistance, while the triangle's amplitude is set by the
    // comparator's threshold divider, which the mode line does not touch. That
    // is why II reads as more agitated rather than wider.
    constexpr float centre = 0.5f * (0.00166f + 0.00535f);
    constexpr float sweep = 0.5f * (0.00535f - 0.00166f);
    constexpr double geometricMean = constexprSqrt(
        siblingMeasuredRateOneHz * siblingMeasuredRateTwoHz);
    constexpr double split = constexprSqrt(modeRateRatio());
    constexpr float rateOne = static_cast<float>(geometricMean / split);
    constexpr float rateTwo = static_cast<float>(geometricMean * split);
    switch (mode)
    {
        case ChorusMode::One:  return { rateOne, centre, sweep, lineGain };
        case ChorusMode::Two:  return { rateTwo, centre, sweep, lineGain };
        // Compatibility with states written while the plug-in exposed both
        // buttons at once. The 106 has no fourth control line or fourth clock
        // programme, so the stronger/faster hardware mode II is the canonical
        // result.
        case ChorusMode::OneTwo:
            return { rateTwo, centre, sweep, lineGain };
        case ChorusMode::Off:
        default:
            // Bypass only mutes the wet return. The oscillator and both BBDs
            // continue to run behind the mute, so an effect prepared while
            // off still needs a real clock programme and sweep depth.
            return { rateOne, centre, sweep, 0.0f };
    }
}

float Chorus::bbdTransfer(float input) noexcept
{
    if (!std::isfinite(input))
        return 0.0f;

    // Evaluate the fractional powers in double precision. Apart from keeping
    // the fit stable at its two calibration points, this lets even an extreme
    // finite float approach the rail instead of overflowing an intermediate
    // power and folding back to zero.
    const double normalised = std::abs(static_cast<double>(input))
                            / static_cast<double>(bbdSaturationLevel);
    const double denominator = std::pow(
        1.0 + std::pow(normalised, static_cast<double>(bbdSaturationExponent)),
        1.0 / static_cast<double>(bbdSaturationExponent));
    return static_cast<float>(static_cast<double>(input) / denominator);
}

float Chorus::transferLossStep(float& state, float input, float clockHz) noexcept
{
    const float dynamicSmear = std::clamp(transferSmear * (1.0f + (clockHz - 26000.0f) * 1.5e-6f), 0.1f, 0.99f);
    state += dynamicSmear * (input - state);
    return state;
}

float Chorus::onePoleG(float cutoffHz, float sampleRate) noexcept
{
    // The wet coupling pole is at 15.9 Hz, so the old 20 Hz defensive floor
    // silently moved a real component value. A small positive floor still
    // protects tan() from invalid callers without voicing the circuit.
    const float limited = std::clamp(cutoffHz, 0.1f, sampleRate * 0.45f);
    const float g = std::tan(3.14159265358979324f * limited / sampleRate);
    return g / (1.0f + g);
}

// One topology-preserving-transform lowpass step. The coefficient above only
// places the corner where it was asked for if the state is advanced by twice
// the difference term: the plain `state += g * (input - state)` recursion wants
// a different coefficient entirely and would put the 9.9 kHz corner near
// 4.6 kHz at the engine's 192 kHz internal rate.
float Chorus::supportFilterStep(float& state, float input, float g) noexcept
{
    const float difference = (input - state) * g;
    const float output = difference + state;
    state = output + difference;
    return output;
}

float Chorus::wetOutputCouplingCornerHz(bool wetConnected) noexcept
{
    const float resistance = wetConnected
        ? wetOutputBleedOhms * wetMixerInputOhms
            / (wetOutputBleedOhms + wetMixerInputOhms)
        : wetOutputBleedOhms;
    return 1.0f / (2.0f * 3.14159265358979323846f
                   * wetOutputCouplingCapacitanceF * resistance);
}

// An equal-resistor Sallen-Key's damping comes entirely from its capacitor
// ratio. Both sections here are built that way -- 22 kOhm twice -- so this is
// the whole of their Q.
float Chorus::sallenKeyQ(float feedbackFarads, float shuntFarads) noexcept
{
    if (shuntFarads <= 0.0f)
        return 0.5f;
    return 0.5f * std::sqrt(feedbackFarads / shuntFarads);
}

Chorus::BiquadCoefficients Chorus::sallenKeyCoefficients(float cutoffHz, float q,
                                                         float sampleRate) noexcept
{
    const float limited = std::clamp(cutoffHz, 20.0f, sampleRate * 0.45f);
    BiquadCoefficients coefficients;
    coefficients.g = std::tan(3.14159265358979324f * limited / sampleRate);
    coefficients.k = 1.0f / std::max(q, 0.05f);
    return coefficients;
}

// Zavalishin's topology-preserving state-variable form, lowpass output. The
// prewarped `g` puts the corner where it was asked for at any host rate, which
// a direct-form biquad with bilinear coefficients would not do as cleanly at
// the engine's 192 kHz internal rate.
float Chorus::biquadStep(BiquadState& state, float input,
                         const BiquadCoefficients& coefficients) noexcept
{
    const float g = coefficients.g;
    const float k = coefficients.k;
    // `k` is the form's own damping term, which is already 1/Q -- doubling it
    // here would halve every section's Q and darken the whole chain.
    const float highPass = (input - (k + g) * state.s1 - state.s2)
                         / (1.0f + g * (g + k));
    const float bandPass = g * highPass + state.s1;
    state.s1 = g * highPass + bandPass;
    const float lowPass = g * bandPass + state.s2;
    state.s2 = g * bandPass + lowPass;
    return lowPass;
}

Chorus::SupportChain Chorus::supportChainFor(float sampleRate) noexcept
{
    SupportChain chain;
    chain.inputCouplingG = onePoleG(inputCouplingHz, sampleRate);
    chain.passiveG = onePoleG(antiAliasPassiveHz, sampleRate);
    chain.idealSourceTapPoleG = onePoleG(idealSourceTapPoleHz, sampleRate);
    chain.wetOutputCouplingMutedG = onePoleG(
        wetOutputCouplingCornerHz(false), sampleRate);
    chain.wetOutputCouplingConnectedG = onePoleG(
        wetOutputCouplingCornerHz(true), sampleRate);
    chain.antiAliasFirst = sallenKeyCoefficients(
        antiAliasFirstHz,
        sallenKeyQ(antiAliasFirstFeedbackF, antiAliasFirstShuntF), sampleRate);
    chain.antiAliasSecond = sallenKeyCoefficients(
        antiAliasSecondHz,
        sallenKeyQ(antiAliasSecondFeedbackF, antiAliasSecondShuntF), sampleRate);
    // The output sections are the same two networks again, part for part.
    chain.reconstructionFirst = sallenKeyCoefficients(
        reconstructionFirstHz,
        sallenKeyQ(antiAliasFirstFeedbackF, antiAliasFirstShuntF), sampleRate);
    chain.reconstructionSecond = sallenKeyCoefficients(
        reconstructionSecondHz,
        sallenKeyQ(antiAliasSecondFeedbackF, antiAliasSecondShuntF), sampleRate);
    return chain;
}

void Chorus::Line::reset(std::uint32_t seed) noexcept
{
    cells.fill(0.0f);
    writeIndex = 0;
    clockPhase = 0.0;
    held = 0.0f;
    previousInput = 0.0f;
    inputCouplingState = 0.0f;
    antiAliasState = 0.0f;
    antiAliasFirst.reset();
    antiAliasSecond.reset();
    tapSumState = 0.0f;
    reconstructionFirst.reset();
    reconstructionSecond.reset();
    outputCouplingState = 0.0f;
    transferState = 0.0f;
    noiseState = seed | 1u;
}

void Chorus::Line::resetAudioRateSupport() noexcept
{
    // These are trapezoidal integration carries whose representation embeds
    // the old sample interval. The engine calls this only at zero output gain
    // after waiting for musical tails. BBD buckets, write/clock position, the
    // clock-rate transfer state, held output and RNG remain free-running.
    previousInput = 0.0f;
    inputCouplingState = 0.0f;
    antiAliasState = 0.0f;
    antiAliasFirst.reset();
    antiAliasSecond.reset();
    tapSumState = 0.0f;
    reconstructionFirst.reset();
    reconstructionSecond.reset();
    outputCouplingState = 0.0f;
}

float Chorus::Line::process(float input, float clockHz, float sampleRate,
                            const SupportChain& support,
                            float outputCouplingG, float noiseScale) noexcept
{
    // Band-limit ahead of the line. Everything above half the clock would fold,
    // exactly as it does in the part. The two Sallen-Key sections precede the
    // wet-only C44/C47 coupling high-pass; the passive 10 kOhm / 2.2 nF pole is
    // last, immediately beside the MN3009 input.
    float limited = Chorus::biquadStep(antiAliasFirst, input, support.antiAliasFirst);
    limited = Chorus::biquadStep(antiAliasSecond, limited, support.antiAliasSecond);
    const float couplingLow = Chorus::supportFilterStep(
        inputCouplingState, limited, support.inputCouplingG);
    limited -= couplingLow;
    limited = Chorus::supportFilterStep(antiAliasState, limited, support.passiveG);

    const double increment =
        static_cast<double>(clockHz) / static_cast<double>(sampleRate);
    clockPhase += increment;
    // A clock above the host rate needs more than one shift per sample, which
    // is exactly what happens at 44.1 or 48 kHz with oversampling switched off.
    // The bound is the worst ratio the model supports -- the fastest clock
    // against the lowest host rate -- so every elapsed edge is consumed and no
    // backlog can build up and drag the delay off its setting.
    int shifts = 0;
    while (clockPhase >= 1.0 && shifts < maximumShiftsPerSample)
    {
        clockPhase -= 1.0;
        ++shifts;

        // Resample the input onto the clock edge. What is left in `clockPhase`
        // is measured in clock cycles, so it has to be divided by the increment
        // to become the fraction of a host sample since the edge -- using it
        // raw would place every edge far too close to the current sample.
        const float fraction = increment > 0.0
            ? static_cast<float>(std::clamp(clockPhase / increment, 0.0, 1.0))
            : 0.0f;
        const float atEdge = limited + (previousInput - limited) * fraction;
        // The line's own overload. The charge a cell can hold is bounded by
        // its bias window, so the wet path saturates before anything around
        // it does; driving the chorus hot grits the delayed signal only.
        const float bounded = Chorus::bbdTransfer(atEdge);

        writeIndex = writeIndex + 1 < cellPairs ? writeIndex + 1 : 0;
        const float emerging = cells[static_cast<std::size_t>(writeIndex)];
        cells[static_cast<std::size_t>(writeIndex)] = bounded;

        Chorus::transferLossStep(transferState, emerging, clockHz);
        noiseState = nextNoiseState(noiseState);
        held = transferState
             + noiseFromState(noiseState) * independentLineRandomAmplitude
               * noiseScale;
    }
    // If the ratio somehow exceeded even that bound, drop the remainder rather
    // than carrying it: a backlog would make the line run slower than the clock
    // it was asked for and drift further out every sample.
    if (clockPhase >= 1.0)
        clockPhase -= std::floor(clockPhase);
    previousInput = limited;

    // Sum the complementary BBD output taps through their 3.3 kOhm resistors,
    // then reconstruct the held staircase through the two output sections.
    const float tapSum = Chorus::supportFilterStep(
        tapSumState, held, support.idealSourceTapPoleG);
    const float first =
        Chorus::biquadStep(reconstructionFirst, tapSum,
                           support.reconstructionFirst);
    const float reconstructed = Chorus::biquadStep(
        reconstructionSecond, first, support.reconstructionSecond);
    const float outputCouplingLow = Chorus::supportFilterStep(
        outputCouplingState, reconstructed, outputCouplingG);
    return reconstructed - outputCouplingLow;
}

void Chorus::prepare(double sampleRate, bool preserveState) noexcept
{
    sampleRate_ = static_cast<float>(std::clamp(sampleRate, 8000.0, 768000.0));
    inverseSampleRate_ = 1.0f / sampleRate_;
    support_ = supportChainFor(sampleRate_);
    if (preserveState)
    {
        lineA_.resetAudioRateSupport();
        lineB_.resetAudioRateSupport();
    }
    else
        reset(false);
}

void Chorus::reset(bool preserveLfoPhase) noexcept
{
    const double continuingPhase = lfoPhase_;
    lineA_.reset(0x9e3779b9u);
    lineB_.reset(0x85ebca6bu);
    lfoPhase_ = preserveLfoPhase ? continuingPhase : 0.0;
    const auto runningWhileMuted = settingsFor(ChorusMode::Off);
    wetGain_ = runningWhileMuted.wetGain;
    rateHz_ = runningWhileMuted.rateHz;
    sweep_ = runningWhileMuted.sweepSeconds;
    centreDelay_ = runningWhileMuted.centreDelaySeconds;
    commonNoiseState_ = 0xd1b54a35u;
    orthogonalNoiseState_ = 0x94d049bbu;
    humPhase_ = 0.0;
    clockSpurPhaseA_ = 0.0;
    clockSpurPhaseB_ = 0.0;
    // A patch loaded with the effect switched on is not a player reaching for
    // the button: there is nothing to glide from. The first sample after a
    // reset takes the mode as it stands, and only changes made afterwards
    // glide.
    primed_ = false;
}

void Chorus::process(float input, ChorusMode mode, float noiseScale,
                     float& left, float& right,
                     bool enableClockBleed,
                     bool enableHyperbolicSweep,
                     float calibration) noexcept
{
    const auto target = settingsFor(mode);

    if (!primed_)
    {
        rateHz_ = target.rateHz;
        sweep_ = target.sweepSeconds;
        centreDelay_ = target.centreDelaySeconds;
        wetGain_ = target.wetGain;
        primed_ = true;
    }

    if (mode != ChorusMode::Off)
    {
        rateHz_ = target.rateHz;
        sweep_ = target.sweepSeconds;
        centreDelay_ = target.centreDelaySeconds;
    }
    const float muteGlide = 1.0f - std::exp(
        -inverseSampleRate_ / wetMuteTimeConstantSeconds);
    const float wetDelta = (target.wetGain - wetGain_);
    wetGain_ += wetDelta * muteGlide;
    const float jfetGatePop = wetDelta * 0.003f;

    lfoPhase_ += rateHz_ * inverseSampleRate_;
    if (lfoPhase_ >= 1.0f)
        lfoPhase_ -= std::floor(lfoPhase_);
    const float modulation = triangle(lfoPhase_);

    // MN3101 current-controlled oscillator delay sweep law. Tr22's voltage-to-
    // current converter makes the *clock* linear in the control voltage, not
    // the delay, so a physically faithful sweep bends delay hyperbolically --
    // but only if it does so about the clock's own endpoints, not the delay's
    // centre. Bending about the centre (an earlier revision of this code) moves
    // the endpoints outward as Unit Character increases -- see OQ-01, which
    // records the measured centre/sweep (3.505 ms / 1.845 ms) rendering a
    // 38%-too-wide 2.30-7.40 ms range at Unit Character 1.0 instead of the
    // measured 1.66-5.35 ms. Sweeping the clock linearly between the two clock
    // frequencies that correspond to the measured delay endpoints keeps both
    // endpoints exact at every blend amount, and differs from the linear-in-
    // delay model only in the trajectory between them.
    float nominalDelayA = centreDelay_ + sweep_ * modulation;
    float nominalDelayB = centreDelay_ - sweep_ * modulation;

    if (enableHyperbolicSweep && calibration > 0.0f && centreDelay_ > 1.0e-5f)
    {
        const float maxDelay = centreDelay_ + sweep_;
        const float minDelay = std::max(centreDelay_ - sweep_, 1.0e-5f);
        const float clockAtMinDelay = clockForDelaySeconds(minDelay);
        const float clockAtMaxDelay = clockForDelaySeconds(maxDelay);
        const float clockMid = 0.5f * (clockAtMinDelay + clockAtMaxDelay);
        const float clockSpread = 0.5f * (clockAtMinDelay - clockAtMaxDelay);

        const float hypDelayA = delaySecondsForClock(clockMid - clockSpread * modulation);
        const float hypDelayB = delaySecondsForClock(clockMid + clockSpread * modulation);

        nominalDelayA += (hypDelayA - nominalDelayA) * std::clamp(calibration, 0.0f, 100.0f);
        nominalDelayB += (hypDelayB - nominalDelayB) * std::clamp(calibration, 0.0f, 100.0f);
    }

    const float delayA = std::max(nominalDelayA, 1.0e-4f);
    const float delayB = std::max(nominalDelayB, 1.0e-4f);
    const float clockA = std::clamp(clockForDelaySeconds(delayA),
                                    minimumClockHz, maximumClockHz);
    const float clockB = std::clamp(clockForDelaySeconds(delayB),
                                    minimumClockHz, maximumClockHz);

    const float wetOutputCouplingG = mode == ChorusMode::Off
        ? support_.wetOutputCouplingMutedG
        : support_.wetOutputCouplingConnectedG;
    float wetA = lineA_.process(input, clockA, sampleRate_, support_,
                                wetOutputCouplingG, noiseScale);
    float wetB = lineB_.process(input, clockB, sampleRate_, support_,
                                wetOutputCouplingG, noiseScale);

    if (enableClockBleed)
    {
        clockSpurPhaseA_ += static_cast<double>(clockA) * inverseSampleRate_;
        clockSpurPhaseB_ += static_cast<double>(clockB) * inverseSampleRate_;
        clockSpurPhaseA_ -= std::floor(clockSpurPhaseA_);
        clockSpurPhaseB_ -= std::floor(clockSpurPhaseB_);
        const float bleedScale = 0.005f * std::max(noiseScale, 0.1f);
        const float heterodyneBleedA = bleedScale * static_cast<float>(std::sin(2.0 * 3.14159265358979323846 * clockSpurPhaseA_));
        const float heterodyneBleedB = bleedScale * static_cast<float>(std::sin(2.0 * 3.14159265358979323846 * clockSpurPhaseB_));
        wetA += heterodyneBleedA;
        wetB += heterodyneBleedB;
    }

    // TR11 / TR12 2SK30A JFET channel resistance modulation & gate charge injection
    const float jfetModA = 1.0f - 0.015f * std::tanh(wetA * wetA);
    const float jfetModB = 1.0f - 0.015f * std::tanh(wetB * wetB);
    wetA = (wetA + jfetGatePop) * jfetModA;
    wetB = (wetB + jfetGatePop) * jfetModB;

    // These mechanisms are deliberately separate from the compatibility hiss
    // above.  Their insertion point, spectra, levels and stereo correlation
    // are all voiced/unknown pending the calibrated OQ-03 capture.  Zero is
    // therefore the production default, and this branch leaves the old render
    // bit-identical when no optional component has been configured.
    const bool hasOptionalNoise = optionalNoise_.commonRandomAmplitude != 0.0f
        || optionalNoise_.humAmplitude != 0.0f
        || optionalNoise_.clockSpurAmplitude != 0.0f;
    if (hasOptionalNoise)
    {
        float optionalA = 0.0f;
        float optionalB = 0.0f;

        if (optionalNoise_.commonRandomAmplitude != 0.0f)
        {
            const auto common = correlatedRandomStep(
                commonNoiseState_, orthogonalNoiseState_,
                optionalNoise_.commonRandomCorrelation);
            optionalA += optionalNoise_.commonRandomAmplitude * common.lineA;
            optionalB += optionalNoise_.commonRandomAmplitude * common.lineB;
        }

        if (optionalNoise_.humAmplitude != 0.0f)
        {
            // A common deterministic term is the smallest useful hypothesis;
            // polarity and channel imbalance remain unknown.
            const float hum = optionalNoise_.humAmplitude
                * deterministicToneStep(humPhase_, optionalNoise_.humFrequencyHz,
                                        sampleRate_);
            optionalA += hum;
            optionalB += hum;
        }

        if (optionalNoise_.clockSpurAmplitude != 0.0f)
        {
            // Each candidate spur follows its own modulated BBD clock.  The
            // harmonic and post-line insertion level are disabled hypotheses,
            // not claims about a measured unit.
            optionalA += optionalNoise_.clockSpurAmplitude
                * deterministicToneStep(
                    clockSpurPhaseA_, clockA * optionalNoise_.clockSpurHarmonic,
                    sampleRate_);
            optionalB += optionalNoise_.clockSpurAmplitude
                * deterministicToneStep(
                    clockSpurPhaseB_, clockB * optionalNoise_.clockSpurHarmonic,
                    sampleRate_);
        }

        wetA += optionalA * noiseScale;
        wetB += optionalB * noiseScale;
    }

    // Both channels carry dry plus wet. The width comes from the two lines
    // being clocked in antiphase, not from inverting one side, so summing to
    // mono thins the effect rather than cancelling it.
    left = dryMixGain * (input + wetA * wetGain_);
    right = dryMixGain * (input + wetB * wetGain_);
}

} // namespace youknow106
