// Generated by Tools/GenerateMeasuredBridge.py; do not hand-edit.
// Passive driving-point mobilities fitted to each guitar's treble-side bridge
// impact and co-located treble accelerometer. Acceleration/force is converted
// to velocity/force by differentiating the hammer, following the archive
// script. Each positive weight multiplies s/(s^2 + 2 damping s + omega^2),
// making the sum positive real. One bank per string material: a steel-string
// and a classical are different instruments, and the engine selects by
// StringMaterial.
// Adapted from Robert Mores, "Archive for the acoustical documentation of
// classical Spanish guitars, flamenco guitars and romantic guitars from
// private and public collections -- bridge mobility" (2021),
// https://doi.org/10.5281/zenodo.4604577, licensed CC BY 4.0; see
// THIRD_PARTY_NOTICES.md.

#pragma once

#include <array>

namespace acustra::detail
{
struct MeasuredBridgeMode
{
    float frequency;
    float q;
    float weight;
};

// g21, a 2018 Lester DeVoe flamenca blanca, spruce/cypress, measured in a
// school music room in Freiburg. A nonnegative least-squares projection
// retained 50 of 65 measured modal candidates after a 2-sample
// instrumentation alignment; relative complex error 0.185926, median
// magnitude error 0.823971 dB over 60--10000 Hz.
inline constexpr std::array<MeasuredBridgeMode, 50> measuredSteelBridgeModes {{
    { 82.7636719f, 16.6192036f, 2.28214169f },
    { 90.8203125f, 21.2712536f, 3.04815626f },
    { 177.978516f, 18.2303963f, 9.0219593f },
    { 208.740234f, 42.0113831f, 9.32808018f },
    { 371.337891f, 5.64632082f, 0.700678945f },
    { 412.353516f, 38.2454453f, 1.45682824f },
    { 484.130859f, 35.5368004f, 3.23555398f },
    { 517.822266f, 29.2930183f, 1.08714092f },
    { 591.064453f, 75.5101089f, 2.89070916f },
    { 656.25f, 64.8964691f, 3.05391407f },
    { 729.492188f, 54.4102859f, 1.22777236f },
    { 766.845703f, 52.1603432f, 1.55464971f },
    { 793.212891f, 16.9328594f, 0.662369728f },
    { 847.412109f, 6.53386974f, 2.96190786f },
    { 867.1875f, 45.7813454f, 1.16050339f },
    { 889.892578f, 13.6616802f, 1.5197742f },
    { 919.921875f, 38.9291115f, 0.842888832f },
    { 955.078125f, 7.10445881f, 0.398196757f },
    { 1034.17969f, 51.3217239f, 1.38757741f },
    { 1084.7168f, 27.2437f, 3.59697533f },
    { 1306.64062f, 26.5326748f, 2.2945199f },
    { 1331.54297f, 67.2880783f, 2.40317607f },
    { 1375.48828f, 55.9440002f, 4.97782612f },
    { 1466.30859f, 24.566206f, 5.26868773f },
    { 1614.99023f, 6.16289949f, 2.45599794f },
    { 1863.28125f, 6.1252079f, 5.63117504f },
    { 1984.86328f, 23.2868176f, 4.06139517f },
    { 2149.6582f, 8.54617691f, 1.16615367f },
    { 2243.4082f, 11.6064377f, 6.44483089f },
    { 2340.08789f, 40.9378471f, 1.54253781f },
    { 2648.4375f, 13.2317429f, 2.38352799f },
    { 3068.84766f, 24.2339191f, 0.301105171f },
    { 3224.85352f, 14.4874325f, 1.81847739f },
    { 3552.97852f, 21.5613937f, 0.635653555f },
    { 3829.10156f, 22.2924881f, 2.13211751f },
    { 4402.58789f, 19.6068363f, 1.19612789f },
    { 4853.02734f, 17.1424961f, 2.96105361f },
    { 4957.03125f, 16.6996918f, 0.324119657f },
    { 5143.06641f, 29.4744549f, 1.64067113f },
    { 5424.31641f, 9.92625713f, 3.48355865f },
    { 5570.06836f, 10.1929483f, 6.67104959f },
    { 5690.18555f, 14.4146662f, 0.253884286f },
    { 6083.49609f, 12.5112944f, 2.50579572f },
    { 6318.60352f, 13.1133347f, 1.07036233f },
    { 6637.20703f, 6.11622429f, 2.37769341f },
    { 6995.36133f, 5.11524343f, 11.8836756f },
    { 7442.13867f, 5.42509604f, 23.7036686f },
    { 7880.85938f, 5.7293973f, 21.988903f },
    { 8814.69727f, 11.2330265f, 9.93476009f },
    { 9385.98633f, 9.68338394f, 2.95893383f },
}};

// g34, a 1971 Manuel Contreras classical Spanish, cedar/Rio palisander,
// measured anechoic in the class-1 free-field laboratory of the Hamburg
// University of Applied Sciences. A nonnegative least-squares projection
// retained 42 of 65 measured modal candidates after a 2-sample
// instrumentation alignment; relative complex error 0.197341, median
// magnitude error 1.094127 dB over 60--10000 Hz.
inline constexpr std::array<MeasuredBridgeMode, 42> measuredNylonBridgeModes {{
    { 78.3691406f, 15.236619f, 0.436744213f },
    { 97.4121094f, 19.4670601f, 2.57038045f },
    { 197.753906f, 11.4931002f, 10.5797005f },
    { 260.742188f, 21.7126312f, 13.548192f },
    { 408.691406f, 24.4350681f, 1.49036777f },
    { 511.962891f, 32.8078766f, 0.600714326f },
    { 576.416016f, 37.5556526f, 2.22035813f },
    { 604.980469f, 10.2473507f, 0.944609523f },
    { 626.220703f, 37.1716614f, 0.521014929f },
    { 659.912109f, 40.9531059f, 0.719487727f },
    { 680.419922f, 56.9445839f, 0.632035732f },
    { 719.970703f, 47.731514f, 2.11073828f },
    { 762.451172f, 39.1146774f, 0.958528876f },
    { 824.707031f, 5.94884872f, 1.08095992f },
    { 847.412109f, 4.52570534f, 2.93454885f },
    { 869.384766f, 30.8100414f, 0.275798887f },
    { 979.248047f, 39.1441917f, 2.97118521f },
    { 1113.28125f, 17.8959904f, 1.82572722f },
    { 1143.31055f, 56.2265892f, 0.602789164f },
    { 1205.56641f, 4.14211464f, 1.59631121f },
    { 1265.625f, 31.266819f, 0.962191045f },
    { 1344.72656f, 26.4103584f, 2.16697049f },
    { 1420.16602f, 7.75626945f, 3.84676862f },
    { 1565.91797f, 15.0850687f, 2.63193083f },
    { 1612.06055f, 30.1834927f, 2.06209159f },
    { 1760.00977f, 76.6434479f, 0.477261484f },
    { 1821.5332f, 20.5338287f, 0.887738883f },
    { 1916.74805f, 43.048439f, 1.13848102f },
    { 2032.4707f, 35.2120361f, 3.88763928f },
    { 2139.4043f, 9.97014713f, 5.92850399f },
    { 2390.625f, 10.7459755f, 12.3521328f },
    { 2613.28125f, 4.87802267f, 3.62213206f },
    { 2945.80078f, 5.51258087f, 7.98054838f },
    { 3112.79297f, 12.7356567f, 4.59395313f },
    { 3392.57812f, 3.74524927f, 1.06933451f },
    { 3571.28906f, 4.22296143f, 14.0892572f },
    { 4107.42188f, 8.35960293f, 6.22489882f },
    { 5689.45312f, 6.32154465f, 13.9389839f },
    { 5963.37891f, 6.84250689f, 0.311044753f },
    { 6163.33008f, 20.6196194f, 4.86563778f },
    { 8241.94336f, 7.84081745f, 44.3561592f },
    { 9681.88477f, 10.5450821f, 36.0358963f },
}};
} // namespace acustra::detail
