// Generated by Tools/GenerateMeasuredBridge.py; do not hand-edit.
// Passive spatial approximations fitted to each guitar's bass and treble
// impacts and two accelerometers behind the saddle (Method.pdf Fig. 3).
// Sensor spacing is unreported; treating the responses as collocated ports
// is a model assumption. The cross-record corner is heuristic, not a unique
// measurement of lost rigidity. Acceleration/
// force is converted to velocity/force by differentiating the hammer,
// following the archive script. The model uses heaving and normalized
// rocking displacement r=a*theta; distance along the saddle is in
// units of the impact half-separation a, so impacts are at u = -1 (bass) and
// u = +1 (treble) and a string at u sees
//     Y(u) = sum over modes of (heave + 2 u cross + u^2 rock)
//                              * s/(s^2 + 2 damping s + omega^2),
// which fits the treble-side response at u = +1 and bass-side at u = -1.
// Each mode's residue matrix [[heave, cross], [cross, rock]] is positive
// semidefinite, so the model's Y(u) is positive real. This constraint does
// not establish passivity or collocation of the measured response matrix.
// The original material settings select two measured nylon-string guitars:
// g21 flamenco is adapted for steel, g34 classical for nylon. The separate
// MeasuredSteelBridgeData.h contains actual steel-string bridge measurements.
// Adapted from Robert Mores, "Archive for the acoustical documentation of
// classical Spanish guitars, flamenco guitars and romantic guitars from
// private and public collections -- bridge mobility" (2021),
// https://doi.org/10.5281/zenodo.4604577, licensed CC BY 4.0; see
// THIRD_PARTY_NOTICES.md.

#pragma once

#include <array>

namespace acustra::detail
{
struct MeasuredBridgeMode
{
    float frequency;
    float q;
    float heave;
    float cross;
    float rock;
};

// g21, a 2018 Lester DeVoe flamenca blanca, spruce/cypress, measured in a
// school music room in Freiburg. A positive-semidefinite least-squares
// projection retained 47 of 65 measured modal candidates after a 2-sample
// instrumentation alignment; 30 of them carry a rocking residue, the rest
// sitting above the 2245 Hz heuristic corner from the two cross-side
// records' disagreement. Over the six model string positions and 60--10000
// Hz, relative complex error 0.198546 and worst median magnitude error
// 1.262650 dB.
inline constexpr std::array<MeasuredBridgeMode, 47> measuredSteelBridgeModes {{
    { 82.7636719f, 16.3791466f, 2.52597451f, -0.102906391f, 0.00419233274f },
    { 90.8203125f, 21.1919231f, 3.44154811f, -0.196920663f, 0.0112675298f },
    { 178.710938f, 18.1869926f, 11.8324451f, -1.36978376f, 0.158573106f },
    { 208.740234f, 40.9126701f, 0.714238763f, 1.36591911f, 5.97370577f },
    { 371.337891f, 5.60255909f, 1.13691723f, -0.0602727421f, 0.00319531048f },
    { 412.353516f, 37.4513245f, 1.62417686f, -0.0631754696f, 0.00245733093f },
    { 484.130859f, 44.6993484f, 3.15256786f, -0.127928257f, 0.00519120879f },
    { 517.822266f, 31.2370129f, 1.49473441f, -0.130525053f, 0.0113978703f },
    { 591.064453f, 73.0299301f, 1.02562523f, 0.138171479f, 1.64789462f },
    { 656.25f, 65.3659592f, 0.0405622572f, 0.312703073f, 2.4106946f },
    { 728.759766f, 52.9704094f, 2.21863699f, -0.474539399f, 0.101498187f },
    { 766.113281f, 58.0559807f, 0.422612965f, 0.0636353269f, 0.962002277f },
    { 793.212891f, 38.5703545f, 1.02933764f, -0.168583289f, 0.0276103057f },
    { 848.144531f, 8.3443079f, 2.1730051f, 0.0514490269f, 0.623455763f },
    { 867.919922f, 41.790947f, 0.0172690544f, 0.147774011f, 1.26452553f },
    { 919.921875f, 33.1099892f, 0.980685055f, 0.159902915f, 0.0614171959f },
    { 955.078125f, 7.00245142f, 0.389265567f, 0.160490215f, 0.0661684722f },
    { 1032.71484f, 43.4472809f, 1.77797008f, -0.141775191f, 0.0130361067f },
    { 1084.7168f, 26.8180923f, 4.72721958f, -0.450282276f, 0.0428907759f },
    { 1269.28711f, 74.6931534f, 0.10973151f, 0.0750771314f, 0.0513669737f },
    { 1330.81055f, 35.4402084f, 0.0595704839f, -0.598575294f, 6.01459599f },
    { 1374.75586f, 56.8241386f, 0.32936722f, 0.0612278357f, 4.1428318f },
    { 1466.30859f, 24.3766499f, 1.35070062f, -0.155843198f, 4.52854013f },
    { 1697.75391f, 6.26817656f, 2.66874242f, -0.181137368f, 0.0122944592f },
    { 1762.93945f, 32.1352158f, 0.148677945f, 0.0314575061f, 0.130737364f },
    { 1899.90234f, 6.17852879f, 1.79859805f, -0.693352222f, 2.50423884f },
    { 1988.52539f, 13.1727295f, 3.11674571f, 0.335056216f, 2.27330208f },
    { 2054.44336f, 7.01390505f, 0.914667606f, 0.0726630241f, 0.00577249611f },
    { 2149.6582f, 7.25377226f, 2.23036861f, 0.213928521f, 0.0205192138f },
    { 2244.14062f, 32.5072021f, 2.66161275f, 0.179692417f, 0.0121315047f },
    { 2341.55273f, 36.0058975f, 1.21546543f, 0.0f, 0.0f },
    { 3209.47266f, 14.482913f, 3.53973317f, 0.0f, 0.0f },
    { 3551.51367f, 59.3911057f, 0.0929317027f, 0.0f, 0.0f },
    { 3722.16797f, 18.1428795f, 3.66621709f, 0.0f, 0.0f },
    { 4039.30664f, 8.26392746f, 0.0948417261f, 0.0f, 0.0f },
    { 4189.45312f, 8.96288586f, 0.690806568f, 0.0f, 0.0f },
    { 4354.98047f, 20.0971279f, 2.52758908f, 0.0f, 0.0f },
    { 4765.13672f, 6.21177387f, 1.52793574f, 0.0f, 0.0f },
    { 4951.9043f, 9.08312416f, 9.03742123f, 0.0f, 0.0f },
    { 5417.72461f, 10.8632631f, 8.43281174f, 0.0f, 0.0f },
    { 5691.65039f, 27.522274f, 1.27656293f, 0.0f, 0.0f },
    { 6065.91797f, 6.10119963f, 6.22871161f, 0.0f, 0.0f },
    { 6317.13867f, 13.6069679f, 1.93027544f, 0.0f, 0.0f },
    { 6756.5918f, 5.71399689f, 18.6041355f, 0.0f, 0.0f },
    { 7551.26953f, 5.1309967f, 47.6505737f, 0.0f, 0.0f },
    { 8229.49219f, 5.20765686f, 0.668715119f, 0.0f, 0.0f },
    { 9120.11719f, 4.91801691f, 19.0153008f, 0.0f, 0.0f },
}};

// g34, a 1971 Manuel Contreras classical Spanish, cedar/Rio palisander,
// measured anechoic in the class-1 free-field laboratory of the Hamburg
// University of Applied Sciences. A positive-semidefinite least-squares
// projection retained 46 of 65 measured modal candidates after a 2-sample
// instrumentation alignment; 40 of them carry a rocking residue, the rest
// sitting above the 5657 Hz heuristic corner from the two cross-side
// records' disagreement. Over the six model string positions and 60--10000
// Hz, relative complex error 0.235357 and worst median magnitude error
// 1.336137 dB.
inline constexpr std::array<MeasuredBridgeMode, 46> measuredNylonBridgeModes {{
    { 78.3691406f, 14.6324568f, 0.422264665f, 0.00373145775f, 3.29740506e-05f },
    { 97.4121094f, 19.1501675f, 2.73422337f, -0.0787101015f, 0.0022658282f },
    { 197.753906f, 11.019393f, 13.5605917f, -1.46163213f, 0.157542437f },
    { 261.474609f, 20.8761635f, 2.3592813f, 3.30803013f, 4.64403629f },
    { 297.363281f, 4.55918694f, 0.941687882f, -0.176372886f, 0.0330336541f },
    { 408.691406f, 28.4756699f, 1.10479641f, 0.0724161118f, 0.00474666059f },
    { 511.230469f, 3.33333325f, 0.25598675f, 0.12497934f, 0.0610181428f },
    { 545.654297f, 6.20237875f, 0.602002501f, -0.325094432f, 0.17555806f },
    { 568.359375f, 27.1715717f, 3.29482865f, -0.550568938f, 0.237444848f },
    { 626.220703f, 4.75646114f, 0.269467026f, 0.240912423f, 0.215383664f },
    { 660.644531f, 5.9575038f, 1.12969863f, 0.930300832f, 0.766097784f },
    { 719.970703f, 49.3817215f, 0.483597279f, 0.440357566f, 0.400983989f },
    { 760.986328f, 39.7774544f, 0.303144127f, -0.0499519669f, 0.546990395f },
    { 810.791016f, 8.16574955f, 1.31084156f, -0.419444174f, 0.432695061f },
    { 868.652344f, 5.59780788f, 0.0656871647f, 0.227352515f, 0.78689903f },
    { 908.935547f, 3.33333325f, 2.46742082f, -1.13498938f, 0.522084057f },
    { 979.980469f, 36.5194626f, 1.21973515f, 0.587379456f, 0.530625045f },
    { 1113.28125f, 18.0188732f, 0.637099087f, 0.251000762f, 0.0988878906f },
    { 1143.31055f, 54.3522644f, 0.177617744f, 0.140442848f, 0.111048542f },
    { 1205.56641f, 3.88807225f, 4.55807495f, -0.370662123f, 0.0301421974f },
    { 1346.19141f, 13.9699879f, 3.4755764f, 0.351665407f, 0.0702310279f },
    { 1565.18555f, 18.7704868f, 0.122033261f, -0.591404796f, 2.86610079f },
    { 1605.46875f, 17.9880714f, 0.00322177145f, 0.0934881195f, 2.71280217f },
    { 1760.00977f, 6.92419577f, 1.43865728f, 0.173812419f, 0.160395592f },
    { 1926.26953f, 42.5261574f, 0.185147136f, 0.0571039356f, 0.560422599f },
    { 2036.86523f, 26.5022926f, 0.332647026f, 0.90229094f, 2.44742608f },
    { 2148.92578f, 11.4607792f, 2.24822259f, 0.532371938f, 0.503216505f },
    { 2389.16016f, 19.9102974f, 0.999668241f, 0.671521962f, 2.09526539f },
    { 2461.66992f, 4.41944027f, 0.393061578f, 2.04725838f, 10.6631298f },
    { 2717.28516f, 5.56423283f, 2.20948458f, -2.49789095f, 2.8239429f },
    { 3038.08594f, 10.401804f, 1.72344124f, 1.95364654f, 2.21460104f },
    { 3131.83594f, 11.0684052f, 0.0575030334f, 0.0684086159f, 0.0813824683f },
    { 3387.45117f, 3.97902679f, 0.180359155f, 0.716737986f, 2.84827995f },
    { 3567.62695f, 5.02256203f, 1.91282058f, 0.321368486f, 1.31474364f },
    { 3810.05859f, 3.33333325f, 3.12467432f, 3.33930945f, 3.56868792f },
    { 4248.7793f, 7.88957548f, 0.00715362979f, 0.0191210471f, 0.0511089414f },
    { 4354.98047f, 9.08274364f, 1.799649f, -2.55506802f, 3.62758112f },
    { 4820.80078f, 4.32851744f, 1.23219371f, -1.6807301f, 2.29254031f },
    { 5394.28711f, 5.70975256f, 0.0271746386f, 0.0222598687f, 0.0182339773f },
    { 5450.68359f, 23.6737919f, 0.521013558f, 0.470642358f, 0.425141007f },
    { 5949.46289f, 7.08899403f, 3.86043978f, 0.0f, 0.0f },
    { 6178.71094f, 17.0966816f, 2.8176856f, 0.0f, 0.0f },
    { 7181.39648f, 19.7197361f, 0.758329093f, 0.0f, 0.0f },
    { 8329.10156f, 5.45545483f, 19.0449409f, 0.0f, 0.0f },
    { 8988.28125f, 3.91766858f, 6.8943696f, 0.0f, 0.0f },
    { 9682.61719f, 4.05865097f, 42.1015549f, 0.0f, 0.0f },
}};
} // namespace acustra::detail
