// Generated by Tools/GenerateMeasuredBridge.py; do not hand-edit.
// Passive driving-point mobility fitted to g21's treble-side bridge impact and
// co-located treble accelerometer. Acceleration/force is converted to
// velocity/force by differentiating the hammer, following the archive script.
// A nonnegative least-squares projection retained 50 of
// 65 measured modal candidates after a 2-sample
// instrumentation alignment;
// relative complex error 0.185926, median magnitude error
// 0.823971 dB over 60--10000 Hz. Each positive weight
// multiplies s/(s^2 + 2 damping s + omega^2), making the sum positive real.
// Adapted from Robert Mores, "Archive for the acoustical documentation of
// classical Spanish guitars, flamenco guitars and romantic guitars from
// private and public collections -- bridge mobility" (2021),
// https://doi.org/10.5281/zenodo.4604577, licensed CC BY 4.0; see
// THIRD_PARTY_NOTICES.md.

#pragma once

#include <array>

namespace acustra::detail
{
struct MeasuredBridgeMode
{
    float frequency;
    float q;
    float weight;
};

inline constexpr std::array<MeasuredBridgeMode, 50> measuredBridgeModes {{
    { 82.7636719f, 16.6192036f, 2.28214169f },
    { 90.8203125f, 21.2712536f, 3.04815626f },
    { 177.978516f, 18.2303963f, 9.0219593f },
    { 208.740234f, 42.0113831f, 9.32808018f },
    { 371.337891f, 5.64632082f, 0.700678945f },
    { 412.353516f, 38.2454453f, 1.45682824f },
    { 484.130859f, 35.5368004f, 3.23555398f },
    { 517.822266f, 29.2930183f, 1.08714092f },
    { 591.064453f, 75.5101089f, 2.89070916f },
    { 656.25f, 64.8964691f, 3.05391407f },
    { 729.492188f, 54.4102859f, 1.22777236f },
    { 766.845703f, 52.1603432f, 1.55464971f },
    { 793.212891f, 16.9328594f, 0.662369728f },
    { 847.412109f, 6.53386974f, 2.96190786f },
    { 867.1875f, 45.7813454f, 1.16050339f },
    { 889.892578f, 13.6616802f, 1.5197742f },
    { 919.921875f, 38.9291115f, 0.842888832f },
    { 955.078125f, 7.10445881f, 0.398196757f },
    { 1034.17969f, 51.3217239f, 1.38757741f },
    { 1084.7168f, 27.2437f, 3.59697533f },
    { 1306.64062f, 26.5326748f, 2.2945199f },
    { 1331.54297f, 67.2880783f, 2.40317607f },
    { 1375.48828f, 55.9440002f, 4.97782612f },
    { 1466.30859f, 24.566206f, 5.26868773f },
    { 1614.99023f, 6.16289949f, 2.45599794f },
    { 1863.28125f, 6.1252079f, 5.63117504f },
    { 1984.86328f, 23.2868176f, 4.06139517f },
    { 2149.6582f, 8.54617691f, 1.16615367f },
    { 2243.4082f, 11.6064377f, 6.44483089f },
    { 2340.08789f, 40.9378471f, 1.54253781f },
    { 2648.4375f, 13.2317429f, 2.38352799f },
    { 3068.84766f, 24.2339191f, 0.301105171f },
    { 3224.85352f, 14.4874325f, 1.81847739f },
    { 3552.97852f, 21.5613937f, 0.635653555f },
    { 3829.10156f, 22.2924881f, 2.13211751f },
    { 4402.58789f, 19.6068363f, 1.19612789f },
    { 4853.02734f, 17.1424961f, 2.96105361f },
    { 4957.03125f, 16.6996918f, 0.324119657f },
    { 5143.06641f, 29.4744549f, 1.64067113f },
    { 5424.31641f, 9.92625713f, 3.48355865f },
    { 5570.06836f, 10.1929483f, 6.67104959f },
    { 5690.18555f, 14.4146662f, 0.253884286f },
    { 6083.49609f, 12.5112944f, 2.50579572f },
    { 6318.60352f, 13.1133347f, 1.07036233f },
    { 6637.20703f, 6.11622429f, 2.37769341f },
    { 6995.36133f, 5.11524343f, 11.8836756f },
    { 7442.13867f, 5.42509604f, 23.7036686f },
    { 7880.85938f, 5.7293973f, 21.988903f },
    { 8814.69727f, 11.2330265f, 9.93476009f },
    { 9385.98633f, 9.68338394f, 2.95893383f },
}};
} // namespace acustra::detail
