// Generated by Tools/GenerateMeasuredSteelBridge.py; do not hand-edit.
// Carcagno, Bucknall, Woodhouse, Fritz and Plack (2018),
// https://doi.org/10.1121/1.5084735; data https://osf.io/f4pqa/, CC BY 4.0.
// Adapted from the first specSet column: custom Fylde Falstaff, Sitka spruce
// top/Brazilian rosewood back and sides, ebony bridge, steel 80/20 strings.
// Manufacture year unspecified. See THIRD_PARTY_NOTICES.md.
// Measured normal velocity/force (m/s/N) between strings 5 and 6, strings
// damped. Scalar heave only: cross/rocking and radiation were not measured.
// The 65.9-Hz peak may include support motion. This is a bridge alternative,
// not a measured full-body or microphone model.
// Y(s) = sum heave*s/(s*s + omega/q*s + omega*omega), omega=2*pi*frequency.
// All residues positive: the mobility is passive at every string position.
// Fit 60 Hz-10 kHz: relative complex error 0.229563,
// median magnitude error 0.978462 dB. Measured SI gain retained;
// Polarity -1 and phase advance 35.872 us inferred by constrained fit;
// the data do not independently identify this as an instrumentation delay.
// Source MAT SHA-256: c306e2c78e72e1526a931b16967dbc4f87c1bc7ecf2c928ff8d492a64e318288
#pragma once

// Include the selected bridge header defining MeasuredBridgeMode first.
#include <array>

namespace acustra::detail
{
inline constexpr std::array<MeasuredBridgeMode, 44> measuredFyldeBridgeModes {{
    { 65.9179688f, 13.8710814f, 0.157175198f, 0.0f, 0.0f },
    { 97.0f, 34.0f, 1.03792882f, 0.0f, 0.0f },
    { 177.0f, 18.0f, 5.34026766f, 0.0f, 0.0f },
    { 336.0f, 36.0f, 1.74372458f, 0.0f, 0.0f },
    { 418.701172f, 5.20312357f, 0.223084554f, 0.0f, 0.0f },
    { 480.957031f, 58.9037209f, 0.201746106f, 0.0f, 0.0f },
    { 502.929688f, 46.5910492f, 0.144606605f, 0.0f, 0.0f },
    { 534.667969f, 57.2827721f, 0.167068005f, 0.0f, 0.0f },
    { 578.613281f, 59.4191093f, 0.143183753f, 0.0f, 0.0f },
    { 634.765625f, 66.4343338f, 0.198145509f, 0.0f, 0.0f },
    { 684.814453f, 19.66078f, 1.52101707f, 0.0f, 0.0f },
    { 703.125f, 20.4191647f, 1.09312809f, 0.0f, 0.0f },
    { 773.925781f, 57.5145416f, 0.140903085f, 0.0f, 0.0f },
    { 812.988281f, 48.8999176f, 0.402422935f, 0.0f, 0.0f },
    { 926.513672f, 80.0f, 0.385301888f, 0.0f, 0.0f },
    { 955.810547f, 50.0767059f, 0.315400749f, 0.0f, 0.0f },
    { 1079.10156f, 51.6148071f, 0.526307642f, 0.0f, 0.0f },
    { 1182.86133f, 44.8842697f, 0.829275191f, 0.0f, 0.0f },
    { 1251.2207f, 48.5307732f, 0.79113543f, 0.0f, 0.0f },
    { 1373.29102f, 48.0836372f, 0.296321452f, 0.0f, 0.0f },
    { 1469.72656f, 41.5356483f, 1.33506477f, 0.0f, 0.0f },
    { 1542.96875f, 44.2045174f, 0.389779389f, 0.0f, 0.0f },
    { 1646.72852f, 32.9273682f, 0.641016543f, 0.0f, 0.0f },
    { 1739.50195f, 39.6148338f, 0.632134557f, 0.0f, 0.0f },
    { 1816.40625f, 7.39310455f, 0.0484441556f, 0.0f, 0.0f },
    { 1932.37305f, 12.4030228f, 1.11322176f, 0.0f, 0.0f },
    { 2189.94141f, 46.3176994f, 0.0134072974f, 0.0f, 0.0f },
    { 2258.30078f, 3.33333325f, 3.07938552f, 0.0f, 0.0f },
    { 2485.35156f, 43.0912056f, 0.630890012f, 0.0f, 0.0f },
    { 2575.68359f, 36.5922928f, 0.606813073f, 0.0f, 0.0f },
    { 2718.50586f, 26.2427597f, 0.94023633f, 0.0f, 0.0f },
    { 2930.9082f, 14.08811f, 1.61331367f, 0.0f, 0.0f },
    { 3320.3125f, 37.5901909f, 0.602750361f, 0.0f, 0.0f },
    { 3524.16992f, 27.8268089f, 0.947399974f, 0.0f, 0.0f },
    { 3725.58594f, 27.2904148f, 0.905439258f, 0.0f, 0.0f },
    { 4030.76172f, 6.58504295f, 2.86638594f, 0.0f, 0.0f },
    { 4216.30859f, 7.07852745f, 2.08439898f, 0.0f, 0.0f },
    { 4398.19336f, 31.5399799f, 0.546264589f, 0.0f, 0.0f },
    { 4827.88086f, 31.5897923f, 1.07855475f, 0.0f, 0.0f },
    { 5439.45312f, 14.7743025f, 4.02259779f, 0.0f, 0.0f },
    { 6254.88281f, 15.7718649f, 2.79559922f, 0.0f, 0.0f },
    { 6936.03516f, 5.58223724f, 8.66536713f, 0.0f, 0.0f },
    { 8673.0957f, 17.725441f, 2.54200768f, 0.0f, 0.0f },
    { 9007.56836f, 5.56970787f, 16.4097061f, 0.0f, 0.0f },
}};
} // namespace acustra::detail
